version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: rust
    labels:
      - dependencies
    rebase-strategy: auto
  - package-ecosystem: npm
    directory: /front-vue
    schedule:
      interval: weekly
    commit-message:
      prefix: npm
    labels:
      - dependencies
    rebase-strategy: auto